#!/bin/bash

xhost +local:all
docker run -it --rm \
	-e DISPLAY=$DISPLAY \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v $HOME/:/home/developer \
	-v "$JAVA_HOME"/:/opt/jdk/ \
	-v /usr/share/fonts/:/usr/share/fonts/ \
	rodrigomiguele/intellij-idea 
